import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Auto-generate sidebar from docs folder structure
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
